// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Organizer.Models;

public partial class DB : DbContext
{

    public DB() {}

    public DB(DbContextOptions<DB> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("Data Source=DESKTOP-QFRCAHK;" +
                "Initial Catalog=Orginizer;" +
                "Integrated Security=True;" +
                "Trust Server Certificate=True;" +
                "Command Timeout=300;" +
                "MultipleActiveResultSets=True");
        }
    }

    public virtual DbSet<Tasks> Tasks { get; set; }

    public virtual DbSet<Statuses> Statuses { get; set; }

    public virtual DbSet<Types> Types { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tasks>(entity =>
        {
            entity.Property(e => e.Id)
                .HasColumnName("ID");
            entity.Property(e => e.Advanced).HasColumnName("ADVANCED");
            entity.Property(e => e.Day).HasColumnName("DAY");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("DESCRIPTION");
            entity.Property(e => e.Status).HasColumnName("STATUS");
            entity.Property(e => e.Type).HasColumnName("TYPE");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ListsOrginizer_STATUSES");

            entity.HasOne(d => d.TypeNavigation).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.Type)
                .HasConstraintName("FK_ListsOrginizer_Types");
        });

        modelBuilder.Entity<Statuses>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_STATUSES");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(25)
                .HasColumnName("STATUS");
        });

        modelBuilder.Entity<Types>(entity =>
        {
            entity.Property(e => e.Id)              
                .HasColumnName("ID");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(25)
                .HasColumnName("TYPE");
            entity.Property(e => e.Status).HasColumnName("STATUS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}