// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Organizer.Models;

public partial class Tasks
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int Day { get; set; }

    public int Status { get; set; }

    public int Type { get; set; }

    public int Advanced { get; set; }

    public virtual Statuses StatusNavigation { get; set; }

    public virtual Types TypeNavigation { get; set; }
}